Repository 2024-WinterBootcamp-Team-E/frontend, pull requests merged in 2025-01, with the labels that each got.

#4 [setting/#2] 기타 라이브러리 세팅
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/GlobalStyle.jsx
  src/Router.jsx
  src/index.css
  src/pages/Home.jsx
  src/store/index.jsx
  vite.config.js
Labels: ⚙ Setting

#6 [setting/#3] Pretendard 폰트 적용
  package-lock.json
  package.json
  src/GlobalStyle.jsx
  src/index.css
Labels: ⚙ Setting

#9 [setting/#4] Storybook 설치 및 세팅
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
Labels: ⚙ Setting, ✅ Test

#10 [feat/#1] Button 컴포넌트 작성
  package-lock.json
  package.json
  src/App.css
  src/components/Button.jsx
  src/pages/Home.jsx
Labels: ✨ Feature, 🎨 Html&css, ⚙ Setting

#12 [feat/#2] Input 컴포넌트 작성
  src/App.css
  src/GlobalStyle.jsx
  src/components/Button.jsx
  src/components/Input.jsx
  src/index.css
Labels: ✨ Feature, 🎨 Html&css, ✅ Test

#19 [setting/#5] Docker 세팅 및 storybook 제거
  .dockerignore
  Dockerfile
  package-lock.json
  package.json
Labels: ⚙ Setting

#20 [feat/#4] ChatBubble 컴포넌트 구현 완료
  eslint.config.js
  src/App.css
  src/GlobalStyle.jsx
  src/components/Bubble.jsx
  src/components/Button.jsx
  src/components/ChatBubble.jsx
  src/components/ChatFeedbackAlert.jsx
  src/index.css
  src/mock/chatData.js
  src/pages/Home.jsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#22 [setting/#6] Router.jsx 세팅
  src/Router.jsx
  src/pages/Intonation/IStudy.jsx
  src/pages/Intonation/index.jsx
  src/pages/Pronounciation/PStudy.jsx
  src/pages/Pronounciation/index.jsx
  src/pages/SignIn/index.jsx
  src/pages/SignUp/index.jsx
Labels: ⚙ Setting

#27 [feat/#7] 컨트롤러 버튼 세팅
  package-lock.json
  package.json
  src/Router.jsx
  src/components/RecordButton.jsx
  src/pages/Home.jsx
  src/pages/RecordTest.jsx
Labels: ✨ Feature

#30 [feat/#11] Layout 컴포넌트 구현
  src/App.css
  src/components/Layout.jsx
  src/pages/Home.jsx
Labels: 🐞 BugFix, ✨ Feature

#33 [Feat/#12]회원가입 페이지 추가
  src/components/Header.jsx
  src/components/Input.jsx
  src/components/Layout.jsx
  src/index.css
  src/pages/SignUp/index.jsx
Labels: ✨ Feature

#35 [Feat]로그인 페이지 기능 추가/#14
  package-lock.json
  package.json
  src/pages/SignIn/index.jsx
Labels: ✨ Feature

#37 [Feat] PStudy 페이지 작성
  package-lock.json
  package.json
  public/SampleAudio.wav
  src/GlobalStyle.jsx
  src/Router.jsx
  src/components/Button.jsx
  src/components/DropDown.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/PlayButton.jsx
  src/index.css
  src/mock/Evaluation.js
  src/pages/Pronounciation/PStudy.jsx
Labels: ✨ Feature

#38 [Feat]회원가입 페이지 기능 추가/#16
  package-lock.json
  package.json
  src/components/Input.jsx
  src/pages/SignUp/index.jsx
Labels: ✨ Feature

#40 [feat/#17] Header 라우팅 추가
  package-lock.json
  src/components/Header.jsx
Labels: ✨ Feature

#44 [feat/#18] IStudy 페이지 구현
  src/components/ChatBubble.jsx
  src/pages/Intonation/IStudy.jsx
Labels: ✨ Feature

#45 [feat/#19] Pronunciation 페이지 구현
  public/PronunImages/business.jpg
  public/PronunImages/movie.jpg
  public/PronunImages/practical.jpg
  public/PronunImages/travel.jpg
  src/Router.jsx
  src/components.zip
  src/pages/Pronounciation/PStudy.jsx
  src/pages/Pronounciation/index.jsx
  src/pages/Pronunciation/PStudy.jsx
  src/pages/Pronunciation/index.jsx
Labels: ✨ Feature

#46 [feat/#20] SoundWave 컴포넌트 구현
  public/SampleAudio.wav
  src/components/PlayButton.jsx
  src/components/RecordButton.jsx
  src/components/SoundWave.jsx
  src/pages/Pronounciation/PStudy.jsx
Labels: ✨ Feature, 🔨 Refactor

#47 [feat/#21] intonation 페이지 퍼블리싱 완료
  package-lock.json
  public/SpeechImages/big.jpg
  public/SpeechImages/state.jpg
  src/pages/Intonation/index.jsx
  src/pages/Pronounciation/PStudy.jsx
  src/pages/Pronunciation/PStudy.jsx
Labels: ✨ Feature

#49 [feat/#22] base64ToBlob.jsx 작성
  .gitignore
  src/Router.jsx
  src/mock/SampleAudio.js
  src/util/AudioUtil.jsx
Labels: ✨ Feature, 📬 API

#54 [feat/#23] 홈페이지 퍼블리싱 완료
  package-lock.json
  public/LandingBackground.jpg
  src/Router.jsx
  src/components/Button.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/pages/Home.jsx
Labels: ✨ Feature

#58 [api/#24] 회원가입 api연동 완료
  src/pages/SignUp/index.jsx
Labels: 📬 API

#60 [api/#25] 헤더컴포넌트에 로고 추가
  public/logo.png
  public/logo2.png
  src/components/Header.jsx
Labels: 🔨 Refactor

#62 [feat/#26] 공통 api 함수 제작
  src/api/index.jsx
  src/pages/SignUp/index.jsx
Labels: ✨ Feature

#63 [feat/#27] SoundWave.jsx 및 PStudy 페이지 완성
  .eslintrc.json
  package-lock.json
  package.json
  public/PronunImages/business2.jpg
  public/PronunImages/movie2.jpg
  public/PronunImages/practical2.jpg
  public/PronunImages/travel2.jpg
  src/Router.jsx
  src/components.zip
  src/components/Button.jsx
  src/components/Header.jsx
  src/components/PlayButton.jsx
  src/components/RecordButton.jsx
  src/components/SoundWave.jsx
  src/pages/Home.jsx
  src/pages/Pronunciation/PStudy.jsx
  src/pages/Pronunciation/index.jsx
  src/store/index.jsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#64 [refactor/#28] 발음 페이지 리뉴얼
  src/Router.jsx
  src/components/ChatBubble.jsx
  src/components/RecordButton.jsx
  src/mock/chatData.js
  src/pages/Intonation/IStudy.jsx
Labels: 🔨 Refactor

#65 [feat/#29] signin api 연동
  package-lock.json
  src/components/Header.jsx
  src/pages/SignIn/index.jsx
  src/pages/SignUp/index.jsx
Labels: ✨ Feature

#69 [refactor/#30] pronounciation -> pstudy 이동 기능 추가
  public/PronunImages/business.jpg
  public/PronunImages/movie.jpg
  public/PronunImages/practical.jpg
  public/PronunImages/travel.jpg
  public/PronunImages/travel2.jpg
  public/PronunImages/travel3.jpg
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/PlayButton.jsx
  src/pages/Intonation/IStudy.jsx
  src/pages/Pronunciation/index.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#71 [bug/#31]signin 기능 수정
  src/pages/SignIn/index.jsx
Labels: 🐞 BugFix

#73 [feat/#32]대시보드 페이지 추가
  src/Router.jsx
  src/pages/Dashboard/index.jsx
Labels: ✨ Feature

#74 [api/#33]헤더컴포넌트 api 연동
  src/components/DropDown.jsx
  src/components/Header.jsx
  src/pages/SignIn/index.jsx
  src/store/authStore.jsx
Labels: 📬 API

#78 [feat/#34]모달 퍼블리싱 완료
  package-lock.json
  package.json
  public/logo.png
  public/uk.png
  public/usa.png
  src/components/Button.jsx
  src/components/DropDown.jsx
  src/pages/Intonation/IStudy.jsx
Labels: ✨ Feature

#80 [api/#35]pronunciation 페이지
  index.html
  package-lock.json
  src/GlobalStyle.jsx
  src/Router.jsx
  src/pages/Pronunciation/PStudy.jsx
  src/pages/Pronunciation/index.jsx
Labels: 📬 API

#82 [api/#36] PStudy 페이지에 api 연결
  package-lock.json
  package.json
  public/19번오디오.wav
  public/애저평가2.wav
  src/Router.jsx
  src/api/index.jsx
  src/components/PlayButton.jsx
  src/components/SoundWave.jsx
  src/pages/Pronunciation/PStudy.jsx
Labels: 🔨 Refactor, 📬 API

#85 [feat/#37] 대시보드 페이지 프로필 연동 구현
  package-lock.json
  src/components/Header.jsx
  src/components/Input.jsx
  src/pages/Dashboard/index.jsx
Labels: ✨ Feature

#89 [api/#38]SSE 공통함수 제작 및 발음 평가 결과 반환 post에 적용
  package-lock.json
  src/api/index.jsx
  src/components/SoundWave.jsx
Labels: 📬 API

#90 refactor:로그인 없이 헤더 클릭 시 로그인페이지로 리다이렉션 구현
  src/components/Header.jsx
  src/pages/Dashboard/index.jsx
Labels: 🔨 Refactor

#93 [feat/#40] 대시보드 페이지 잔디 심기 구현
  package-lock.json
  package.json
  src/components/Attendance.jsx
  src/pages/Dashboard/index.jsx
Labels: ✨ Feature

#94 [Feat/#41] 그래프 완성 중 중간 저장
  package-lock.json
  package.json
  src/components/Button.jsx
  src/components/DashboardGraphs.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/index.css
  src/mock/weakPoints.js
  src/pages/Dashboard/index.jsx
  src/pages/Home.jsx
  src/pages/Intonation/IStudy.jsx
  src/pages/Intonation/index.jsx
  src/pages/Pronunciation/index.jsx
  src/pages/SignIn/index.jsx
  src/pages/SignUp/index.jsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#95 [Feat/#42] PStudy 페이지 완료
  src/api/index.jsx
  src/components/SoundWave.jsx
  src/index.css
  src/pages/Pronunciation/PStudy.jsx
  src/pages/Pronunciation/index.jsx
  src/store/index.jsx
Labels: ✨ Feature

#96 [Feat/#42] 대시보드 My Histories 그래프들 그리기 완료
  package-lock.json
  package.json
  src/api/index.jsx
  src/components/DashboardGraphs.jsx
  src/components/Header.jsx
  src/index.css
  src/mock/weakPoints.js
  src/pages/Dashboard/index.jsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor, 📬 API

#99 [Access/#43] <head/> 및 메타데이터 설정
  index.html
  public/EAStudy.png
Labels: 🥰 Accessibility

#101 [fix/#44] 마이페이지 userId 하드코딩 버그 해결
  src/pages/Dashboard/index.jsx
Labels: 🐞 BugFix

#103 [fix/#45] attendance 기능 수정
  src/components/Attendance.jsx
  src/pages/Dashboard/index.jsx
Labels: 🐞 BugFix

#106 [refactor/#46] 청크 띄어쓰기 무시 수정 및 피드백란 넘침 수정
  src/api/index.jsx
  src/components/SoundWave.jsx
  src/pages/Pronunciation/PStudy.jsx
Labels: 🔨 Refactor

#108 [Feat/#47] IStudy 새 채팅방 만들기 완료
  src/api/index.jsx
  src/pages/Intonation/IStudy.jsx
  src/pages/Intonation/index.jsx
  src/store/index.jsx
Labels: ✨ Feature

#110 [Refactor/#48] 라우팅 수정 및 pstudy index.jsx 반응 추가
  src/Router.jsx
  src/components/DashboardGraphs.jsx
  src/components/Header.jsx
  src/pages/Pronunciation/index.jsx
Labels: 🔨 Refactor

#112 [Feat/#49] IStudy페이지 기능 완성 및 api 연동 완료 및 페이지 코드 수정
  src/mock/Evaluation.js
  src/mock/SampleAudio.js
  src/mock/chatData.js
  src/pages/Dashboard/index.jsx
  src/pages/Intonation/IStudy.jsx
  src/store/index.jsx
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#116 [Refactor/#51] 발음피드백 토글 바로 생성
  src/components/ChatBubble.jsx
  src/pages/Intonation/IStudy.jsx
Labels: 🔨 Refactor

#117 [Refactor/#6] 자잘한 최적화 + 개발자 모드 소스코드 가리기
  package.json
Labels: 🌏 Deploy, 🔨 Refactor

#118 [Refactor/#53] 이미지 저장기능 추가
  src/assets/react.svg
  src/pages/Dashboard/index.jsx
  src/pages/SignIn/index.jsx
Labels: ✨ Feature, 🔨 Refactor

#121 [Bug/#54] 로그인 된 상태에서 Get started 버튼 누르면 아무 기능 없는 현상 수정
  src/pages/Home.jsx
Labels: 🐞 BugFix

#124 [Refactor/#56] 자잘한 수정들
  public/19번오디오.wav
  public/AIImage.jpg
  public/SampleAudio.wav
  public/uk_icon.png
  public/us_icon.png
  public/vite.svg
  public/애저평가2.wav
  src/components/Button.jsx
  src/components/ChatBubble.jsx
  src/components/Input.jsx
  src/pages/Intonation/IStudy.jsx
  src/pages/SignIn/index.jsx
  src/pages/SignUp/index.jsx
Labels: 🔨 Refactor

#127 [Feat/#57] 채팅방 삭제 기능 구현
  src/components/Button.jsx
  src/pages/Intonation/IStudy.jsx
Labels: ✨ Feature

#135 [refactor/#60] 국가에 따른 IStudy AI의 프로필 이미지 적용
  package-lock.json
  public/미국.jpg
  public/영국.jpg
  src/components/ChatBubble.jsx
  src/pages/Intonation/IStudy.jsx
Labels: 🔨 Refactor

#136 [Refactor/#61] tts 중 recordbutton 비활성화
  src/components/RecordButton.jsx
  src/pages/Intonation/IStudy.jsx
Labels: 🔨 Refactor

#137 [Bug/#62] pstudy 재생 끝나면 일시정지 버튼에서 재생 버튼으로 돌아오지 않는 현상 수정
  src/pages/Pronunciation/PStudy.jsx
Labels: 🐞 BugFix

#139 [Bug/#63] pstudy 재생 끝나면 일시정지 버튼에서 재생 버튼으로 돌아오지 않는 현상 수정 2
  src/pages/Pronunciation/PStudy.jsx
Labels: 🐞 BugFix

#140 [Bug/#63] 채팅방삭제
  src/pages/Intonation/IStudy.jsx
Labels: 🐞 BugFix
